module.exports = {
  SET_ROLE: 'SET_ROLE',
  // POST JOB OR HIRE MOONER TYPES
  SET_BUDGET: 'SET_BUDGET',
  SET_JOB_DESCRIPTION: 'SET_JOB_DESCRIPTION',
  SET_SERVICE_SEEKER_ID: 'SET_SERVICE_SEEKER_ID',
  SET_JOB_CAT: 'SET_JOB_CAT',
  SET_JOB_SUBCAT: 'SET_JOB_SUBCAT',
  SET_JOBANSWERS: 'SET_JOBANSWERS',
  SET_DATE_TIME: 'SET_DATE_TIME',
  RESET_POST_JOB: 'RESET_POST_JOB',
  SET_MOONER_LIST: 'SET_MOONER_LIST',
  MOONER_FILTER_LOADER: 'MOONER_FILTER_LOADER',
  // My Booking SS
  SET_ACTIVE_JOBS: 'SET_ACTIVE_JOBS',
  SET_ONGOING_JOBS: 'SET_ONGOING_JOBS',
  SET_COMPLETED_JOBS: 'SET_COMPLETED_JOBS',
  MY_BOOKING_LOADER_START: 'MY_BOOKING_LOADER_START',
  MY_BOOKING_LOADER_STOP: 'MY_BOOKING_LOADER_STOP',
  SET_MOONER_BIDS_LIST: 'SET_MOONER_BIDS_LIST',
  MOONER_BID_LOADER: 'MOONER_BID_LOADER',
};
