require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
  permissions_path = '../node_modules/react-native-permissions/ios'

platform :ios, '10.0'

target 'Mooner' do


  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])





  pod 'react-native-video', :path => '../node_modules/react-native-video'
  pod 'Firebase/Analytics'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

  target 'MoonerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'Mooner-tvOS' do
  # Pods for Mooner-tvOS

  target 'Mooner-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
